# Generated by Django 4.2.3 on 2023-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_options_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(max_length=300, verbose_name='Текст публикации'),
        ),
    ]
